services:
  firmware-container:
    build: .
    container_name: firmware-dev
    restart: always
    privileged: true
    volumes:
      - ./src:/capstone
      - ./sdk/se-rodeo-iot-sdk:/opt/se-rodeo-iot-sdk
      - ./jlink/JLink_Linux_V812g_arm64.deb:/tmp/JLink_Linux_V812g_arm64.deb
    # devices:
    #   - "/dev:/dev"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    stdin_open: true
    tty: true